### ISSUE TITLE
AERO_UI_TC16 : Calendar widget missing in Add new Flight plan

### ISSUE THREAD

**Issue by hrishiballal** [openskies-sh/aerobridge#10]
![Picture1](https://user-images.githubusercontent.com/1588744/121387683-c8463180-c942-11eb-8cdf-d24529a933f3.jpg)

**Comment by hrishiballal** [comment]
This is now fixed: 
![image](https://user-images.githubusercontent.com/1588744/121500347-1e17e980-c9d6-11eb-9dc1-3131ed8a3eae.png)

**Comment by akshitmahajan** [comment]
@hrishiballal - This is still not fixed under Add New Flight plan page.

<img width="799" alt="Screen Shot 2021-06-16 at 2 38 45 PM" src="https://user-images.githubusercontent.com/6078058/122191932-cdf6c680-ceb0-11eb-9269-6021e716ab75.png">

**Comment by hrishiballal** [comment]
I have investigated this a bit more. It seems like a [Firefox specific bug](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#browser_compatibility). I am assuming that it will be fixed in the coming releases.
